"""Hatchling build hook — generates src/logscope/_meta.py before each build."""

from __future__ import annotations

import subprocess
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class CustomBuildHook(BuildHookInterface):
    """Generate _meta.py with version and git commit SHA at build time."""

    def initialize(self, version: str, build_data: dict) -> None:  # noqa: ARG002
        root = Path(self.root)
        meta_path = root / "src" / "logscope" / "_meta.py"

        try:
            result = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                capture_output=True,
                text=True,
                cwd=root,
                check=True,
            )
            commit = result.stdout.strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            commit = "unknown"

        meta_path.write_text(
            "# Auto-generated by hatch_build.py — do not edit manually.\n"
            f'__version__ = "{self.metadata.version}"\n'
            f'__commit__ = "{commit}"\n',
            encoding="utf-8",
        )
