#!/usr/bin/env python3
"""Generate src/logscope/_meta.py with version and git commit SHA.

Run with: uv run python scripts/gen_meta.py
"""

import subprocess
from pathlib import Path

ROOT = Path(__file__).parent.parent


def get_version() -> str:
    """Read version from pyproject.toml."""
    import tomllib

    with open(ROOT / "pyproject.toml", "rb") as f:
        data = tomllib.load(f)
    return data["project"]["version"]


def get_commit() -> str:
    """Get current git HEAD commit SHA."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            cwd=ROOT,
            check=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def main() -> None:
    """Generate _meta.py."""
    version = get_version()
    commit = get_commit()

    meta_path = ROOT / "src" / "logscope" / "_meta.py"
    meta_path.write_text(
        f"# Auto-generated by scripts/gen_meta.py — do not edit manually.\n"
        f'__version__ = "{version}"\n'
        f'__commit__ = "{commit}"\n'
    )
    print(f"Generated {meta_path} — version={version} commit={commit[:12]}")


if __name__ == "__main__":
    main()
